// Generated by gencpp from file flightgoggles/IRMarkerArray.msg
// DO NOT EDIT!


#ifndef FLIGHTGOGGLES_MESSAGE_IRMARKERARRAY_H
#define FLIGHTGOGGLES_MESSAGE_IRMARKERARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <flightgoggles/IRMarker.h>

namespace flightgoggles
{
template <class ContainerAllocator>
struct IRMarkerArray_
{
  typedef IRMarkerArray_<ContainerAllocator> Type;

  IRMarkerArray_()
    : header()
    , markers()  {
    }
  IRMarkerArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , markers(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::flightgoggles::IRMarker_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::flightgoggles::IRMarker_<ContainerAllocator> >::other >  _markers_type;
  _markers_type markers;





  typedef boost::shared_ptr< ::flightgoggles::IRMarkerArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flightgoggles::IRMarkerArray_<ContainerAllocator> const> ConstPtr;

}; // struct IRMarkerArray_

typedef ::flightgoggles::IRMarkerArray_<std::allocator<void> > IRMarkerArray;

typedef boost::shared_ptr< ::flightgoggles::IRMarkerArray > IRMarkerArrayPtr;
typedef boost::shared_ptr< ::flightgoggles::IRMarkerArray const> IRMarkerArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flightgoggles::IRMarkerArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flightgoggles::IRMarkerArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace flightgoggles

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'flightgoggles': ['/home/robotclass/RoboticsForSWEs/fastsim/src/flightgoggles/flightgoggles/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::flightgoggles::IRMarkerArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flightgoggles::IRMarkerArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flightgoggles::IRMarkerArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flightgoggles::IRMarkerArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flightgoggles::IRMarkerArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flightgoggles::IRMarkerArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flightgoggles::IRMarkerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8091f0feface0cc0f973be1d2b5c29b5";
  }

  static const char* value(const ::flightgoggles::IRMarkerArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8091f0feface0cc0ULL;
  static const uint64_t static_value2 = 0xf973be1d2b5c29b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::flightgoggles::IRMarkerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flightgoggles/IRMarkerArray";
  }

  static const char* value(const ::flightgoggles::IRMarkerArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flightgoggles::IRMarkerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ROS Message that contains pixel-space IR marker locations and labels.\n\
\n\
Header header\n\
flightgoggles/IRMarker[] markers\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: flightgoggles/IRMarker\n\
# ROS Message that contains pixel-space IR marker locations and labels.\n\
\n\
# ID of the landmark (e.g. gate) that the IR marker is attached to\n\
std_msgs/String landmarkID\n\
# ID of individual marker.\n\
std_msgs/String markerID\n\
\n\
float32 x\n\
float32 y\n\
# Z is the distance from the camera in meters.\n\
float32 z\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::flightgoggles::IRMarkerArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flightgoggles::IRMarkerArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.markers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IRMarkerArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flightgoggles::IRMarkerArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flightgoggles::IRMarkerArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "markers[]" << std::endl;
    for (size_t i = 0; i < v.markers.size(); ++i)
    {
      s << indent << "  markers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::flightgoggles::IRMarker_<ContainerAllocator> >::stream(s, indent + "    ", v.markers[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLIGHTGOGGLES_MESSAGE_IRMARKERARRAY_H
