// Generated by gencpp from file sensor_simulators/calibrateResponse.msg
// DO NOT EDIT!


#ifndef SENSOR_SIMULATORS_MESSAGE_CALIBRATERESPONSE_H
#define SENSOR_SIMULATORS_MESSAGE_CALIBRATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_simulators
{
template <class ContainerAllocator>
struct calibrateResponse_
{
  typedef calibrateResponse_<ContainerAllocator> Type;

  calibrateResponse_()
    : baseline(0.0)  {
    }
  calibrateResponse_(const ContainerAllocator& _alloc)
    : baseline(0.0)  {
  (void)_alloc;
    }



   typedef double _baseline_type;
  _baseline_type baseline;





  typedef boost::shared_ptr< ::sensor_simulators::calibrateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_simulators::calibrateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct calibrateResponse_

typedef ::sensor_simulators::calibrateResponse_<std::allocator<void> > calibrateResponse;

typedef boost::shared_ptr< ::sensor_simulators::calibrateResponse > calibrateResponsePtr;
typedef boost::shared_ptr< ::sensor_simulators::calibrateResponse const> calibrateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_simulators::calibrateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_simulators::calibrateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensor_simulators

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensor_simulators::calibrateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_simulators::calibrateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_simulators::calibrateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_simulators::calibrateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_simulators::calibrateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_simulators::calibrateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_simulators::calibrateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2d73167cca4d93dc55c783a92c0ef21";
  }

  static const char* value(const ::sensor_simulators::calibrateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2d73167cca4d93dULL;
  static const uint64_t static_value2 = 0xc55c783a92c0ef21ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_simulators::calibrateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_simulators/calibrateResponse";
  }

  static const char* value(const ::sensor_simulators::calibrateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_simulators::calibrateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 baseline\n\
\n\
";
  }

  static const char* value(const ::sensor_simulators::calibrateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_simulators::calibrateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.baseline);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct calibrateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_simulators::calibrateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_simulators::calibrateResponse_<ContainerAllocator>& v)
  {
    s << indent << "baseline: ";
    Printer<double>::stream(s, indent + "  ", v.baseline);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_SIMULATORS_MESSAGE_CALIBRATERESPONSE_H
