// Generated by gencpp from file sensor_simulators/calibrateRequest.msg
// DO NOT EDIT!


#ifndef SENSOR_SIMULATORS_MESSAGE_CALIBRATEREQUEST_H
#define SENSOR_SIMULATORS_MESSAGE_CALIBRATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_simulators
{
template <class ContainerAllocator>
struct calibrateRequest_
{
  typedef calibrateRequest_<ContainerAllocator> Type;

  calibrateRequest_()
    : zero(false)  {
    }
  calibrateRequest_(const ContainerAllocator& _alloc)
    : zero(false)  {
  (void)_alloc;
    }



   typedef uint8_t _zero_type;
  _zero_type zero;





  typedef boost::shared_ptr< ::sensor_simulators::calibrateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_simulators::calibrateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct calibrateRequest_

typedef ::sensor_simulators::calibrateRequest_<std::allocator<void> > calibrateRequest;

typedef boost::shared_ptr< ::sensor_simulators::calibrateRequest > calibrateRequestPtr;
typedef boost::shared_ptr< ::sensor_simulators::calibrateRequest const> calibrateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_simulators::calibrateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_simulators::calibrateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensor_simulators

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensor_simulators::calibrateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_simulators::calibrateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_simulators::calibrateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_simulators::calibrateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_simulators::calibrateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_simulators::calibrateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_simulators::calibrateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9ff4c2241c03e6209e4e04727bac371";
  }

  static const char* value(const ::sensor_simulators::calibrateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9ff4c2241c03e62ULL;
  static const uint64_t static_value2 = 0x09e4e04727bac371ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_simulators::calibrateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_simulators/calibrateRequest";
  }

  static const char* value(const ::sensor_simulators::calibrateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_simulators::calibrateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool zero\n\
";
  }

  static const char* value(const ::sensor_simulators::calibrateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_simulators::calibrateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.zero);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct calibrateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_simulators::calibrateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_simulators::calibrateRequest_<ContainerAllocator>& v)
  {
    s << indent << "zero: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.zero);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_SIMULATORS_MESSAGE_CALIBRATEREQUEST_H
