// Generated by gencpp from file sensor_simulators/calibrate.msg
// DO NOT EDIT!


#ifndef SENSOR_SIMULATORS_MESSAGE_CALIBRATE_H
#define SENSOR_SIMULATORS_MESSAGE_CALIBRATE_H

#include <ros/service_traits.h>


#include <sensor_simulators/calibrateRequest.h>
#include <sensor_simulators/calibrateResponse.h>


namespace sensor_simulators
{

struct calibrate
{

typedef calibrateRequest Request;
typedef calibrateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct calibrate
} // namespace sensor_simulators


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensor_simulators::calibrate > {
  static const char* value()
  {
    return "75b28b77c2f551fa5005ce2f520330b5";
  }

  static const char* value(const ::sensor_simulators::calibrate&) { return value(); }
};

template<>
struct DataType< ::sensor_simulators::calibrate > {
  static const char* value()
  {
    return "sensor_simulators/calibrate";
  }

  static const char* value(const ::sensor_simulators::calibrate&) { return value(); }
};


// service_traits::MD5Sum< ::sensor_simulators::calibrateRequest> should match 
// service_traits::MD5Sum< ::sensor_simulators::calibrate > 
template<>
struct MD5Sum< ::sensor_simulators::calibrateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_simulators::calibrate >::value();
  }
  static const char* value(const ::sensor_simulators::calibrateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_simulators::calibrateRequest> should match 
// service_traits::DataType< ::sensor_simulators::calibrate > 
template<>
struct DataType< ::sensor_simulators::calibrateRequest>
{
  static const char* value()
  {
    return DataType< ::sensor_simulators::calibrate >::value();
  }
  static const char* value(const ::sensor_simulators::calibrateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensor_simulators::calibrateResponse> should match 
// service_traits::MD5Sum< ::sensor_simulators::calibrate > 
template<>
struct MD5Sum< ::sensor_simulators::calibrateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_simulators::calibrate >::value();
  }
  static const char* value(const ::sensor_simulators::calibrateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_simulators::calibrateResponse> should match 
// service_traits::DataType< ::sensor_simulators::calibrate > 
template<>
struct DataType< ::sensor_simulators::calibrateResponse>
{
  static const char* value()
  {
    return DataType< ::sensor_simulators::calibrate >::value();
  }
  static const char* value(const ::sensor_simulators::calibrateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSOR_SIMULATORS_MESSAGE_CALIBRATE_H
